// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PostController from "./post_controller"
application.register("post", PostController)

import SearchGroupsController from "./search_groups_controller"
application.register("search-groups", SearchGroupsController)

import ShowController from "./show_controller"
application.register("show", ShowController)
